title: Gavins Homepage
description: updates from me
highlighter: rouge
#permalink: /blog/:year/:month/:day/:title/
permalink: /:categories/:title/
environment: prod
markdown: kramdown
url: "https://gavayres.github.io"  # Sitemap base URL.
plugins:
  - jekyll-sitemap
  - jekyll-feed
kramdown:
  math_engine: mathjax
include: [_pages]
collections:
  notes:
    output: true
    permalink: /:collection/:path/
